/**
 * Canary - A free and open-source MMORPG server emulator
 * Copyright (c) 2019-present OpenTibiaBR
 * License: https://github.com/opentibiabr/canary/blob/main/LICENSE
 */

#include "creatures/players/bots/bot_planner.hpp"

namespace {
BotGoalPriority authoritativePriority(BotGoalType type, const BotPlannerObservation &o) {
	if (o.dead && type == BotGoalType::Recover) return BotGoalPriority::DeathRecovery;
	if (o.survivalCritical && type == BotGoalType::Survive) return BotGoalPriority::CriticalSurvival;
	if (o.supplyUrgent && type == BotGoalType::Resupply) return BotGoalPriority::UrgentResupply;
	if (o.activeQuest && type == BotGoalType::CompleteConfiguredQuest) return BotGoalPriority::ActiveQuest;
	if (o.equipmentUpgrade && (type == BotGoalType::EquipUpgrade || type == BotGoalType::Resupply)) return BotGoalPriority::Equipment;
	if (o.progressionConfigured && (type == BotGoalType::GainConfiguredProgress || type == BotGoalType::HuntConfiguredRegion)) return BotGoalPriority::Progression;
	if (o.optionalLoot && (type == BotGoalType::SellConfiguredLoot || type == BotGoalType::DepositConfiguredItems)) return BotGoalPriority::OptionalEconomy;
	return type == BotGoalType::IdleSafely ? BotGoalPriority::Idle : BotGoalPriority::Idle;
}
bool eligible(const BotGoal &g,const BotPlannerObservation&o,const BotPlannerPolicy&p){if(g.id==0||g.type==BotGoalType::Unsupported||g.status==BotGoalStatus::Completed||g.status==BotGoalStatus::Cancelled||g.failures>=p.maximumGoalRetries)return false;if(!o.regionAvailable&&(g.type==BotGoalType::HuntConfiguredRegion||g.type==BotGoalType::ReturnHomeRegion))return false;for(const auto&predicate:g.predicates){bool value=true;switch(predicate.type){case BotGoalPredicateType::Alive:value=!o.dead;break;case BotGoalPredicateType::SurvivalSafe:value=!o.survivalCritical;break;case BotGoalPredicateType::SupplyAvailable:value=!o.supplyUrgent;break;case BotGoalPredicateType::QuestActive:value=o.activeQuest;break;case BotGoalPredicateType::RegionAvailable:value=o.regionAvailable;break;case BotGoalPredicateType::EquipmentAvailable:value=o.equipmentUpgrade;break;case BotGoalPredicateType::ProgressBelowTarget:value=o.progressionConfigured;break;case BotGoalPredicateType::CheckpointValid:value=o.checkpointValid;break;}if(value!=predicate.expected)return false;}return true;}
}

uint16_t BotPlanner::score(const BotGoal &goal,const BotPlannerObservation &observation,const BotPlannerPolicy &){const auto priority=authoritativePriority(goal.type,observation);return static_cast<uint16_t>(static_cast<uint16_t>(priority)*100U+std::min<uint16_t>(static_cast<uint16_t>(goal.priority),99));}

BotPlan BotPlanner::expand(const BotGoal &goal,const BotPlannerPolicy &policy){BotPlan plan{.goalId=goal.id,.goalType=goal.type,.revision=goal.policyRevision,.steps={}};auto add=[&](BotPlanStepType type,uint8_t depth=1,bool safe=false){if(depth>policy.maximumPlanDepth){plan.depthLimitExceeded=true;return;}if(plan.steps.size()>=policy.maximumSteps){plan.stepLimitExceeded=true;return;}plan.steps.push_back({.type=type,.depth=depth,.configuredTargetId=goal.configuredTargetId,.region=goal.configuredRegion,.safeBoundary=safe});};add(BotPlanStepType::Observe,0,true);switch(goal.type){case BotGoalType::Survive:add(BotPlanStepType::Recover);break;case BotGoalType::Recover:add(BotPlanStepType::Recover);add(BotPlanStepType::Travel);break;case BotGoalType::Resupply:add(BotPlanStepType::Travel);add(BotPlanStepType::Resupply);break;case BotGoalType::EquipUpgrade:add(BotPlanStepType::Resupply);add(BotPlanStepType::Equip);break;case BotGoalType::CompleteConfiguredQuest:add(BotPlanStepType::Travel);add(BotPlanStepType::Converse,2);add(BotPlanStepType::Fight,2);add(BotPlanStepType::Loot,2);add(BotPlanStepType::VerifyQuest);break;case BotGoalType::GainConfiguredProgress:case BotGoalType::HuntConfiguredRegion:add(BotPlanStepType::Travel);add(BotPlanStepType::Fight);add(BotPlanStepType::Loot);break;case BotGoalType::SellConfiguredLoot:add(BotPlanStepType::Travel);add(BotPlanStepType::Interact);break;case BotGoalType::DepositConfiguredItems:add(BotPlanStepType::Travel);add(BotPlanStepType::Resupply);break;case BotGoalType::ReturnHomeRegion:add(BotPlanStepType::Travel);break;case BotGoalType::IdleSafely:break;case BotGoalType::Unsupported:return{};}add(BotPlanStepType::SaveLogout,1,true);add(BotPlanStepType::Complete,1,true);return plan;}

BotPlannerDecision BotPlanner::select(std::vector<BotGoal> goals,const BotPlannerObservation &observation,const BotPlannerPolicy &policy,const BotPlannerDecision *current){BotPlannerDecision result;if(!observation.placed||observation.revision==0){result.failure=BotPlannerFailure::InvalidLifecycle;return result;}if(goals.size()>policy.maximumGoals){result.failure=BotPlannerFailure::GoalLimit;return result;}const bool unsupported=std::ranges::any_of(goals,[](const auto&goal){return goal.type==BotGoalType::Unsupported;});std::ranges::sort(goals,[](const auto&a,const auto&b){return a.id<b.id;});const BotGoal*best=nullptr;uint16_t bestScore=0;for(const auto&goal:goals){if(!eligible(goal,observation,policy))continue;const auto value=score(goal,observation,policy);if(!best||value>bestScore||(value==bestScore&&goal.id<best->id)){best=&goal;bestScore=value;}}if(!best){result.failure=unsupported?BotPlannerFailure::UnsupportedGoal:BotPlannerFailure::NoEligibleGoal;return result;}if(current&&!current->terminal()&&current->goalId!=0){const auto it=std::ranges::find(goals,current->goalId,&BotGoal::id);if(it!=goals.end()&&eligible(*it,observation,policy)){const auto currentScore=score(*it,observation,policy);if(bestScore<=static_cast<uint16_t>(std::min<uint32_t>(UINT16_MAX,currentScore+policy.hysteresis)))best=&*it;}}result.goalId=best->id;result.goalType=best->type;result.status=BotGoalStatus::Selected;result.plan=expand(*best,policy);if(result.plan.steps.empty()){result.status=BotGoalStatus::Failed;result.failure=BotPlannerFailure::UnsupportedGoal;return result;}if(result.plan.depthLimitExceeded){result.status=BotGoalStatus::Failed;result.failure=BotPlannerFailure::DepthLimit;return result;}if(result.plan.stepLimitExceeded){result.status=BotGoalStatus::Failed;result.failure=BotPlannerFailure::StepLimit;return result;}result.checkpoint={.goalId=best->id,.goalType=best->type,.policyRevision=policy.revision,.observationRevision=observation.revision,.sessionGeneration=observation.sessionGeneration,.safeSaveBoundary=true};return result;}

BotPlannerDecision BotPlanner::verifyStep(BotPlannerDecision result,uint16_t stepIndex,uint64_t revision,bool verified){if(result.terminal())return result;if(revision<=result.checkpoint.observationRevision){result.failure=BotPlannerFailure::ObservationStale;result.status=BotGoalStatus::Stale;return result;}if(!verified||stepIndex!=result.checkpoint.verifiedStepIndex||stepIndex>=result.plan.steps.size())return result;result.checkpoint.observationRevision=revision;++result.checkpoint.verifiedStepIndex;result.checkpoint.safeSaveBoundary=result.plan.steps[stepIndex].safeBoundary;result.status=result.checkpoint.verifiedStepIndex==result.plan.steps.size()?BotGoalStatus::Completed:BotGoalStatus::Active;return result;}

BotPlannerDecision BotPlanner::replan(std::vector<BotGoal> goals,const BotPlannerObservation &observation,BotPlannerDecision current,BotReplanReason reason,const BotPlannerPolicy &policy){if(current.replanCount>=policy.maximumReplans){current.status=BotGoalStatus::Failed;current.failure=BotPlannerFailure::ReplanLimit;return current;}if(reason==BotReplanReason::Death)current.status=BotGoalStatus::Cancelled;else if(reason==BotReplanReason::SurvivalOverride)current.status=BotGoalStatus::Suspended;auto result=select(std::move(goals),observation,policy,&current);result.replanCount=static_cast<uint8_t>(current.replanCount+1);result.replanReason=reason;if(reason!=BotReplanReason::CheckpointInvalid&&result.goalId==current.goalId&&current.checkpoint.safeSaveBoundary&&current.checkpoint.policyRevision==policy.revision&&current.checkpoint.verifiedStepIndex<=result.plan.steps.size()){result.checkpoint=current.checkpoint;result.checkpoint.observationRevision=observation.revision;result.checkpoint.sessionGeneration=observation.sessionGeneration;}return result;}

BotPlannerDecision BotPlanner::reconstruct(const BotPlannerDecision &saved,const BotPlannerObservation &observation,const BotPlannerPolicy &policy){auto result=saved;if(observation.revision<=saved.checkpoint.observationRevision){result.status=BotGoalStatus::Stale;result.failure=BotPlannerFailure::ObservationStale;return result;}if(!observation.checkpointValid||!saved.checkpoint.safeSaveBoundary||saved.checkpoint.policyRevision!=policy.revision||saved.checkpoint.verifiedStepIndex>saved.plan.steps.size()){result.status=BotGoalStatus::Failed;result.failure=BotPlannerFailure::CheckpointInvalid;result.replanReason=BotReplanReason::CheckpointInvalid;return result;}result.checkpoint.observationRevision=observation.revision;result.checkpoint.sessionGeneration=observation.sessionGeneration;result.status=saved.checkpoint.verifiedStepIndex==saved.plan.steps.size()?BotGoalStatus::Completed:BotGoalStatus::Active;result.failure=BotPlannerFailure::None;return result;}
