#include "creatures/players/bots/bot_coordination.hpp"

namespace{bool eligible(const BotCoordinationMemberObservation&m,const BotCoordinationPolicy&p){return m.configured&&m.playerBot&&m.alive&&m.placed&&std::ranges::contains(p.configuredMembers,m.id);}BotCoordinationRole roleFor(const BotCoordinationMemberObservation&m,BotCoordinationMemberId leader){if(m.id==leader)return BotCoordinationRole::Leader;switch(m.vocationId){case 1:return BotCoordinationRole::Frontline;case 2:return BotCoordinationRole::Damage;case 3:return BotCoordinationRole::Healer;default:return BotCoordinationRole::Unassigned;}}}

BotCoordinationDecision BotCoordination::evaluate(const BotCoordinationPolicy&p,const BotCoordinationGroupObservation&o,BotCoordinationMemberId previous,uint8_t changes){BotCoordinationDecision d;if(p.id==0||p.revision==0||o.id!=p.id){d.state=BotCoordinationState::Failed;d.failure=BotCoordinationFailure::InvalidGroup;return d;}std::vector<BotCoordinationMemberObservation> members;for(const auto&m:o.members)if(eligible(m,p))members.push_back(m);std::ranges::sort(members,{},&BotCoordinationMemberObservation::id);if(members.size()>p.maximumMembers){d.state=BotCoordinationState::Failed;d.failure=BotCoordinationFailure::MemberLimit;return d;}auto explicitLeader=std::ranges::find(members,p.configuredLeader,&BotCoordinationMemberObservation::id);if(explicitLeader!=members.end())d.leaderId=explicitLeader->id;else if(p.fallbackElection&&!members.empty())d.leaderId=members.front().id;if(d.leaderId==0){d.state=BotCoordinationState::LeaderUnavailable;d.failure=BotCoordinationFailure::LeaderUnavailable;return d;}if(previous&&previous!=d.leaderId&&changes>=p.maximumLeaderChanges){d.state=BotCoordinationState::Degraded;d.failure=BotCoordinationFailure::BudgetReached;return d;}d.state=std::ranges::any_of(members,[](const auto&m){return m.healthPercent<25;})?BotCoordinationState::Retreating:BotCoordinationState::Active;for(const auto&m:members){d.roles.emplace_back(m.id,roleFor(m,d.leaderId));BotCoordinationIntent i{.memberId=m.id,.type=d.state==BotCoordinationState::Retreating?BotCoordinationIntentType::Retreat:(m.id==d.leaderId?BotCoordinationIntentType::SharedObjective:BotCoordinationIntentType::Follow),.policyRevision=p.revision};d.intents.push_back(i);}return d;}

BotCoordinationFailure BotCoordination::reserve(std::vector<BotCoordinationReservation>&r,BotCoordinationReservation value,const BotCoordinationPolicy&p,uint64_t now){expire(r,now);if(value.groupId!=p.id||value.memberId==0||value.targetSignature==0||value.policyRevision!=p.revision)return BotCoordinationFailure::InvalidGroup;if(value.expiresAt<=now||value.expiresAt-now>p.maximumReservationDuration)return BotCoordinationFailure::Expired;if(r.size()>=p.maximumReservations)return BotCoordinationFailure::ReservationLimit;auto conflict=std::ranges::find_if(r,[&](const auto&x){return x.type==value.type&&x.targetSignature==value.targetSignature;});if(conflict!=r.end()){if(p.focusFire&&value.type==BotCoordinationReservationType::CombatTarget){r.push_back(value);return BotCoordinationFailure::None;}return conflict->memberId==value.memberId?BotCoordinationFailure::None:BotCoordinationFailure::Conflict;}r.push_back(value);std::ranges::sort(r,[](const auto&a,const auto&b){return std::tie(a.type,a.targetSignature,a.memberId)<std::tie(b.type,b.targetSignature,b.memberId);});return BotCoordinationFailure::None;}
void BotCoordination::invalidate(std::vector<BotCoordinationReservation>&r,BotCoordinationMemberId id,uint64_t generation){std::erase_if(r,[=](const auto&x){return x.memberId==id&&(generation==0||x.sessionGeneration!=generation);});}
void BotCoordination::expire(std::vector<BotCoordinationReservation>&r,uint64_t now){std::erase_if(r,[=](const auto&x){return x.expiresAt<=now;});}
