/**
 * Canary - A free and open-source MMORPG server emulator
 * Copyright (©) 2019–present OpenTibiaBR
 * License: https://github.com/opentibiabr/canary/blob/main/LICENSE
 */

#include "creatures/players/bots/bot_resupply.hpp"

#include "creatures/players/player.hpp"
#include "game/game.hpp"
#include "items/containers/container.hpp"
#include "items/containers/depot/depotchest.hpp"
#include "items/item.hpp"

namespace {
std::shared_ptr<Item> inventoryItem(const std::shared_ptr<Player> &player,const BotInventoryPath &path){if(!player||path.rootSlot<CONST_SLOT_FIRST||path.rootSlot>CONST_SLOT_LAST)return nullptr;auto item=player->getInventoryItem(static_cast<Slots_t>(path.rootSlot));for(const auto index:path.childIndices){if(!item||!item->getContainer())return nullptr;item=item->getContainer()->getItemByIndex(index);}return item;}
std::shared_ptr<Item> depotItem(const std::shared_ptr<Player> &player,const BotDepotPath &path){if(!player||path.boxId==0)return nullptr;std::shared_ptr<Item> item=player->getDepotChest(path.boxId,false);for(const auto index:path.childIndices){if(!item||!item->getContainer())return nullptr;item=item->getContainer()->getItemByIndex(index);}return item;}
std::shared_ptr<Cylinder> inventoryDestination(const std::shared_ptr<Player> &player,const BotInventoryPath &path){if(path.rootSlot==0)return player;if(auto item=inventoryItem(player,path);item&&item->getContainer())return item->getContainer();return nullptr;}
std::shared_ptr<Cylinder> depotDestination(const std::shared_ptr<Player> &player,const BotDepotPath &path){if(path.boxId==0)return nullptr;if(path.childIndices.empty())return player->getDepotChest(path.boxId,false);if(auto item=depotItem(player,path);item&&item->getContainer())return item->getContainer();return nullptr;}
BotResupplyOutcome moveFailure(ReturnValue value){if(value==RETURNVALUE_NOTENOUGHCAPACITY)return BotResupplyOutcome::CapacityInsufficient;if(value==RETURNVALUE_NOTENOUGHROOM||value==RETURNVALUE_DEPOTISFULL)return BotResupplyOutcome::ContainerFull;if(value==RETURNVALUE_ITEMISNOTYOURS)return BotResupplyOutcome::DepotOwnershipRejected;return BotResupplyOutcome::WorldRejected;}
}

uint64_t BotResupply::itemSignature(const BotDepotItemObservation &item) {
	uint64_t value=1469598103934665603ULL; const auto add=[&](uint64_t part){value^=part;value*=1099511628211ULL;}; add(item.itemTypeId);add(item.count);add(item.path.boxId);for(const auto index:item.path.childIndices)add(index);return value;
}

BotDepotObservation BotResupply::observeDepot(const std::shared_ptr<Player> &player,uint32_t depotId,const BotResupplyPolicy &policy) {
	BotDepotObservation result;result.depotId=depotId;if(!player||!player->getTile()||!player->isNearDepotBox()||player->getLastDepotId()!=static_cast<int16_t>(depotId))return result;const auto root=player->getDepotChest(1,false);if(!root)return result;result.open=true;
	struct Pending{std::shared_ptr<Container> container;BotDepotPath path;uint8_t depth;};std::vector<Pending> pending{{root,{1,{}},0}};uint16_t seenItems=0;uint8_t seenContainers=0;
	for(size_t cursor=0;cursor<pending.size()&&!result.itemBudgetExceeded;++cursor){if(seenContainers++>=policy.maximumDepotContainers){result.containerBudgetExceeded=true;break;}const auto current=pending[cursor];result.containers.push_back({current.path,static_cast<uint16_t>(std::min<uint32_t>(UINT16_MAX,current.container->capacity())),static_cast<uint16_t>(current.container->size()),current.depth});for(uint16_t index=0;index<current.container->size();++index){if(seenItems++>=policy.maximumItemsObserved){result.itemBudgetExceeded=true;break;}const auto item=current.container->getItemByIndex(index);if(!item)continue;auto path=current.path;path.childIndices.push_back(index);BotDepotItemObservation observed{item->getID(),item->getItemCount(),path};observed.signature=itemSignature(observed);result.items.push_back(observed);if(const auto child=item->getContainer();child&&current.depth<policy.maximumNestingDepth)pending.push_back({child,path,static_cast<uint8_t>(current.depth+1)});}}
	std::ranges::sort(result.containers,{},&BotDepotContainerObservation::path);std::ranges::sort(result.items,[](const auto&a,const auto&b){return std::tuple(a.path,a.itemTypeId)<std::tuple(b.path,b.itemTypeId);});uint64_t revision=1469598103934665603ULL;for(const auto &item:result.items){revision^=item.signature;revision*=1099511628211ULL;}result.revision=revision;return result;
}

BotResupplyPlan BotResupply::plan(const BotEquipmentObservation &inventory,const BotDepotObservation &depot,const BotResupplyPolicy &policy){BotResupplyPlan result;if(!depot.open){result.outcome=BotResupplyOutcome::DepotUnavailable;return result;}for(const auto &target:policy.targets){uint64_t carried=0,stored=0;BotInventoryPath inventoryPath;BotDepotPath depotPath;for(const auto &item:inventory.items)if(item.itemTypeId==target.itemTypeId){carried=std::min<uint64_t>(UINT32_MAX,carried+item.countOrCharges);inventoryPath=item.path;}for(const auto &item:depot.items)if(item.itemTypeId==target.itemTypeId){stored=std::min<uint64_t>(UINT32_MAX,stored+item.count);if(depotPath.boxId==0)depotPath=item.path;}++result.operationCount;if(carried<target.minimum&&stored>target.reserve){const uint64_t desired=std::max(target.minimum,target.target);const auto count=std::min<uint64_t>({desired-carried,stored-target.reserve,policy.maximumTransferCount});if(count)result.transfers.push_back({BotResupplyDirection::DepotToInventory,depot.depotId,target.itemTypeId,static_cast<uint32_t>(count),{},depotPath,inventory.revision,depot.revision});}}
	for(const auto id:policy.depositItemTypeIds){for(const auto &item:inventory.items)if(item.itemTypeId==id&&!item.equipped){const auto count=std::min<uint32_t>(item.countOrCharges,policy.maximumTransferCount);if(count)result.transfers.push_back({BotResupplyDirection::InventoryToDepot,depot.depotId,id,count,item.path,{1,{}},inventory.revision,depot.revision});break;}}
	std::ranges::sort(result.transfers,[](const auto&a,const auto&b){return std::tuple(a.itemTypeId,a.direction,a.inventoryPath,a.depotPath)<std::tuple(b.itemTypeId,b.direction,b.inventoryPath,b.depotPath);});result.outcome=result.transfers.empty()?BotResupplyOutcome::SupplyTargetReached:BotResupplyOutcome::Pending;return result;}

std::chrono::milliseconds BotResupply::backoff(const BotResupplyPolicy &policy,uint8_t attempt){uint64_t delay=policy.initialBackoff.count();for(uint8_t i=0;i<attempt&&delay<static_cast<uint64_t>(policy.maximumBackoff.count());++i)delay=std::min<uint64_t>(delay*2,policy.maximumBackoff.count());return std::chrono::milliseconds(delay);}

BotResupplyResult BotResupply::executeTransfer(Game &game,const std::shared_ptr<Player> &player,const BotResupplyRequest &request,const BotResupplyPolicy &policy){BotResupplyResult result{.request=request};if(!player||!player->getTile()){result.outcome=BotResupplyOutcome::Cancelled;result.state=BotResupplyState::Failed;return result;}const auto depot=observeDepot(player,request.depotId,policy);const auto inventory=BotEquipment::observe(player);if(!depot.open){result.outcome=BotResupplyOutcome::DepotUnavailable;result.state=BotResupplyState::Failed;return result;}if(depot.revision!=request.depotRevision){result.outcome=BotResupplyOutcome::SourceStale;result.state=BotResupplyState::Failed;return result;}if(inventory.revision!=request.inventoryRevision){result.outcome=BotResupplyOutcome::DestinationStale;result.state=BotResupplyState::Failed;return result;}const auto sourceItem=request.direction==BotResupplyDirection::DepotToInventory?depotItem(player,request.depotPath):inventoryItem(player,request.inventoryPath);const auto destination=request.direction==BotResupplyDirection::DepotToInventory?inventoryDestination(player,request.inventoryPath):depotDestination(player,request.depotPath);if(!sourceItem||sourceItem->getID()!=request.itemTypeId){result.outcome=BotResupplyOutcome::SourceStale;result.state=BotResupplyState::Failed;return result;}if(!destination){result.outcome=BotResupplyOutcome::DestinationStale;result.state=BotResupplyState::Failed;return result;}const auto source=sourceItem->getParent();result.sourceBefore=source->getItemTypeCount(request.itemTypeId);result.destinationBefore=destination->getItemTypeCount(request.itemTypeId);const uint32_t count=std::min<uint32_t>(request.count,policy.maximumTransferCount);const auto world=game.internalMoveItem(source,destination,INDEX_WHEREEVER,sourceItem,count,nullptr,0,player);result.worldReturnValue=static_cast<uint16_t>(world);result.sourceAfter=source->getItemTypeCount(request.itemTypeId);result.destinationAfter=destination->getItemTypeCount(request.itemTypeId);if(world!=RETURNVALUE_NOERROR){result.outcome=moveFailure(world);result.state=BotResupplyState::Failed;return result;}const auto removed=result.sourceBefore>result.sourceAfter?result.sourceBefore-result.sourceAfter:0;const auto added=result.destinationAfter>result.destinationBefore?result.destinationAfter-result.destinationBefore:0;result.movedCount=std::min(removed,added);if(!result.movedCount)result.outcome=BotResupplyOutcome::NoEffect;else result.outcome=result.movedCount>=count?BotResupplyOutcome::Succeeded:BotResupplyOutcome::Partial;result.state=result.movedCount?BotResupplyState::ResupplyComplete:BotResupplyState::Failed;return result;}

BotEquipmentExecutionResult BotResupply::executeEquipment(Game &game,const std::shared_ptr<Player> &player,const BotEquipmentExecutionRequest &request,const BotEquipmentPolicy &policy){
	BotEquipmentExecutionResult result{.request=request};
	if(!player||!player->getTile()){result.outcome=BotResupplyOutcome::Cancelled;result.failure=BotEquipmentFailure::InvalidLifecycle;result.state=BotResupplyState::Failed;return result;}
	const auto observed=BotEquipment::observe(player,policy);
	const auto fresh=std::ranges::find_if(observed.items,[&](const auto &entry){return entry.itemTypeId==request.candidate.itemTypeId&&entry.path==request.candidate.path;});
	if(observed.revision!=request.candidate.observationRevision||request.candidate.comparison.intent!=BotEquipmentIntent::UpgradeAvailable||fresh==observed.items.end()){result.outcome=BotResupplyOutcome::SourceStale;result.failure=BotEquipmentFailure::FreshAssessmentRequired;result.state=BotResupplyState::Failed;return result;}
	if(!fresh->vocationCompatible||!fresh->levelCompatible){result.outcome=BotResupplyOutcome::RequirementNotMet;result.failure=BotEquipmentFailure::RequirementNotMet;result.state=BotResupplyState::Failed;return result;}
	if(fresh->slot!=request.candidate.slot||fresh->slot==BotEquipmentSlot::None){result.outcome=BotResupplyOutcome::SlotConflict;result.failure=BotEquipmentFailure::SlotConflict;result.state=BotResupplyState::Failed;return result;}
	const auto item=inventoryItem(player,request.candidate.path);const auto replacement=inventoryDestination(player,request.replacementDestination);
	if(!item||item->getID()!=request.candidate.itemTypeId){result.outcome=BotResupplyOutcome::SourceStale;result.failure=BotEquipmentFailure::ItemUnavailable;result.state=BotResupplyState::Failed;return result;}
	if(!replacement||replacement!=item->getParent()){result.outcome=BotResupplyOutcome::DestinationStale;result.failure=BotEquipmentFailure::FreshAssessmentRequired;result.state=BotResupplyState::Failed;return result;}
	const auto slot=static_cast<Slots_t>(request.candidate.slot);const auto before=player->getInventoryItem(slot);result.equippedBefore=before?before->getID():0;result.replacedItemTypeId=result.equippedBefore;
	const auto world=game.internalMoveItem(item->getParent(),player,slot,item,item->getItemCount(),nullptr,0,player);result.worldReturnValue=static_cast<uint16_t>(world);const auto after=player->getInventoryItem(slot);result.equippedAfter=after?after->getID():0;
	if(world!=RETURNVALUE_NOERROR){const bool twoHanded=world==RETURNVALUE_DROPTWOHANDEDITEM||world==RETURNVALUE_BOTHHANDSNEEDTOBEFREE||world==RETURNVALUE_PUTTHISOBJECTINBOTHHANDS;const bool slotConflict=world==RETURNVALUE_CANONLYUSEONEWEAPON||world==RETURNVALUE_CANONLYUSEONESHIELD||world==RETURNVALUE_CANNOTBEDRESSED;result.outcome=twoHanded?BotResupplyOutcome::TwoHandedConflict:slotConflict?BotResupplyOutcome::SlotConflict:moveFailure(world);result.failure=twoHanded?BotEquipmentFailure::TwoHandedConflict:slotConflict?BotEquipmentFailure::SlotConflict:world==RETURNVALUE_NOTENOUGHCAPACITY?BotEquipmentFailure::CapacityInsufficient:BotEquipmentFailure::WorldRejected;result.state=BotResupplyState::Failed;return result;}
	if(result.equippedAfter!=request.candidate.itemTypeId){result.outcome=BotResupplyOutcome::EquipmentNotChanged;result.failure=BotEquipmentFailure::WorldRejected;result.state=BotResupplyState::Failed;return result;}
	result.outcome=BotResupplyOutcome::Succeeded;result.state=BotResupplyState::ResupplyComplete;return result;
}
