#include "creatures/players/bots/bot_progression.hpp"

#include "creatures/players/player.hpp"

namespace {
skills_t canarySkill(BotSkillType type) {
	switch (type) { case BotSkillType::Sword:return SKILL_SWORD;case BotSkillType::Axe:return SKILL_AXE;case BotSkillType::Club:return SKILL_CLUB;case BotSkillType::Distance:return SKILL_DISTANCE;case BotSkillType::Shielding:return SKILL_SHIELD;case BotSkillType::MagicLevel:return SKILL_MAGLEVEL; }
	return SKILL_FIST;
}
}

void BotHuntAreaWindow::record(BotHuntAreaObservation observation) { if(maximumSamples==0)return;while(samples.size()>=maximumSamples)samples.erase(samples.begin());samples.push_back(std::move(observation)); }
void BotHuntAreaWindow::clearFor(BotHuntAreaId areaId) { std::erase_if(samples,[areaId](const auto&s){return s.areaId!=areaId;}); }

BotProgressionObservation BotProgression::observe(const std::shared_ptr<Player>&player,uint64_t revision,WeaponType_t weaponType){BotProgressionObservation r{.revision=revision,.weaponType=weaponType};if(!player||revision==0)return r;r.level=player->getLevel();r.experience=player->getExperience();r.vocationId=player->getVocationId();for(auto type:{BotSkillType::Sword,BotSkillType::Axe,BotSkillType::Club,BotSkillType::Distance,BotSkillType::Shielding,BotSkillType::MagicLevel})r.skills.push_back({.type=type,.level=player->getSkillLevel(canarySkill(type))});return r;}

BotProgressionAssessment BotProgression::assess(const BotProgressionTarget&t,const BotProgressionObservation&o,uint64_t previous){BotProgressionAssessment r{.observationRevision=o.revision};if(o.revision==0||o.revision==previous){r.levelState=BotProgressionState::ObservationStale;return r;}if(t.level.level==0||t.policyRevision==0)return r;r.levelState=o.level>=t.level.level?BotProgressionState::Attained:BotProgressionState::BelowTarget;r.levelProgressPermille=o.level>=t.level.level?1000:static_cast<uint32_t>(std::min<uint64_t>(999,static_cast<uint64_t>(o.level)*1000/t.level.level));bool all=r.levelState==BotProgressionState::Attained;for(const auto&s:t.skills){auto at=std::ranges::find(o.skills,s.type,&BotSkillObservation::type);BotProgressionState state;if(s.level==0||at==o.skills.end())state=BotProgressionState::Invalid;else if(s.requiredVocationId&&s.requiredVocationId!=o.vocationId)state=BotProgressionState::Inapplicable;else if(s.requiredWeaponType!=WEAPON_NONE&&s.requiredWeaponType!=o.weaponType)state=BotProgressionState::Blocked;else if(at->level>=s.level)state=BotProgressionState::Attained;else if(at->tries||at->percent)state=BotProgressionState::Progressing;else state=BotProgressionState::BelowTarget;r.skillStates.push_back(state);all=all&&state==BotProgressionState::Attained;}r.terminal=all;r.startProgressionCombat=!all&&r.levelState==BotProgressionState::BelowTarget&&std::ranges::none_of(r.skillStates,[](auto s){return s==BotProgressionState::Invalid||s==BotProgressionState::Inapplicable||s==BotProgressionState::Blocked;});return r;}

BotHuntAreaAssessment BotProgression::assessArea(const BotHuntAreaPolicy&p,const BotHuntAreaWindow&w,uint32_t level,uint16_t vocation){BotHuntAreaAssessment r;if(p.id==0||p.revision==0||level<p.minimumLevel||level>p.maximumLevel||(!p.vocationIds.empty()&&!std::ranges::contains(p.vocationIds,vocation))){r.suitability=BotHuntAreaSuitability::PolicyMismatch;r.failure=BotHuntAreaFailure::PolicyMismatch;return r;}uint32_t encounters=0,kills=0,failed=0,flees=0,deaths=0,heals=0,supplies=0,noTargets=0,routes=0,ticks=0;uint64_t xp=0;for(const auto&s:w.samples)if(s.areaId==p.id&&s.policyRevision==p.revision){++r.sampleCount;r.observationRevision=std::max(r.observationRevision,s.revision);encounters+=s.encounters;kills+=s.successfulKills;failed+=s.failedCombats;flees+=s.fleeCount;deaths+=s.deathCount;heals+=s.healingUses;supplies+=s.supplyUses;noTargets+=s.noTargetCycles;routes+=s.routeFailures;ticks=std::min<uint32_t>(UINT32_MAX,ticks+s.elapsedTicks);xp=std::min<uint64_t>(UINT64_MAX,xp+s.observedExperience);}if(r.sampleCount<3){r.suitability=BotHuntAreaSuitability::ObservationInsufficient;r.failure=BotHuntAreaFailure::InsufficientEvidence;return r;}if(deaths>=2){r.suitability=BotHuntAreaSuitability::RepeatedDeath;r.failure=BotHuntAreaFailure::Death;r.score=-1000;}else if(flees>=3||failed>=3){r.suitability=BotHuntAreaSuitability::TooDangerous;r.failure=BotHuntAreaFailure::Danger;r.score=-700;}else if(routes>=3){r.suitability=BotHuntAreaSuitability::RouteUnreliable;r.failure=BotHuntAreaFailure::RouteFailure;r.score=-600;}else if(noTargets>=3&&encounters==0){r.suitability=BotHuntAreaSuitability::NoEligibleTargets;r.failure=BotHuntAreaFailure::NoTargets;r.score=-500;}else if(supplies+heals>=6&&kills<2){r.suitability=BotHuntAreaSuitability::SupplyInefficient;r.failure=BotHuntAreaFailure::SupplyFailure;r.score=-400;}else if(kills>=3&&xp==0){r.suitability=BotHuntAreaSuitability::TooWeak;r.failure=BotHuntAreaFailure::WeakProgress;r.score=-300;}else if(ticks>=1000&&xp<10){r.suitability=BotHuntAreaSuitability::ProgressTooSlow;r.failure=BotHuntAreaFailure::WeakProgress;r.score=-200;}else{r.score=static_cast<int32_t>(std::clamp<int64_t>(static_cast<int64_t>(kills)*100+static_cast<int64_t>(xp)-static_cast<int64_t>(failed)*80-static_cast<int64_t>(flees)*100-static_cast<int64_t>(routes)*60-static_cast<int64_t>(supplies+heals)*10,-1000,1000));r.suitability=BotHuntAreaSuitability::Suitable;}return r;}

BotAreaSwitchDecision BotProgression::decideSwitch(BotAreaSwitchState&s,const BotAreaSwitchPolicy&p,const BotHuntAreaAssessment&a,bool pending){BotAreaSwitchDecision r{.fromAreaId=s.activeAreaId,.failure=a.failure};if(s.terminal){r.result=BotAreaSwitchResult::Exhausted;return r;}if(p.revision==0||p.areas.empty()||s.activeAreaId==0){r.result=BotAreaSwitchResult::InvalidPolicy;return r;}if(s.policyRevision!=p.revision){s.policyRevision=p.revision;s.failures.clear();s.cooldownRemaining=0;}if(a.observationRevision==0||a.observationRevision==s.lastObservationRevision)return r;s.lastObservationRevision=a.observationRevision;const bool severe=a.suitability==BotHuntAreaSuitability::RepeatedDeath;if((a.sampleCount<p.minimumEvidence&&!severe)||a.suitability==BotHuntAreaSuitability::Suitable||a.suitability==BotHuntAreaSuitability::Unknown||a.suitability==BotHuntAreaSuitability::ObservationInsufficient)return r;if(pending){r.result=BotAreaSwitchResult::WaitForBoundary;return r;}if(s.cooldownRemaining){--s.cooldownRemaining;r.result=BotAreaSwitchResult::Cooldown;return r;}auto f=std::ranges::find(s.failures,s.activeAreaId,[](const auto&e){return e.first;});if(f==s.failures.end())s.failures.emplace_back(s.activeAreaId,1);else if(f->second!=UINT8_MAX)++f->second;for(const auto&area:p.areas){if(area.id==s.activeAreaId||area.id==s.previousAreaId)continue;auto exhausted=std::ranges::find(s.failures,area.id,[](const auto&e){return e.first;});if(exhausted!=s.failures.end()&&exhausted->second>=p.maximumRetriesPerArea)continue;r.result=BotAreaSwitchResult::Switch;r.toAreaId=area.id;r.freshObservationRequired=true;s.previousAreaId=s.activeAreaId;s.activeAreaId=area.id;s.cooldownRemaining=p.cooldownObservations;return r;}s.terminal=true;r.result=BotAreaSwitchResult::Exhausted;return r;}
