/**
 * Canary - A free and open-source MMORPG server emulator
 * Copyright (©) 2019–present OpenTibiaBR
 * License: https://github.com/opentibiabr/canary/blob/main/LICENSE
 */
#include "creatures/players/bots/bot_dialogue.hpp"
#include "creatures/npcs/npc.hpp"
#include "creatures/players/player.hpp"
#include "game/game.hpp"
#include "map/spectators.hpp"
#include "utils/tools.hpp"

namespace{uint64_t hashToken(std::string_view value){uint64_t hash=1469598103934665603ULL;for(const auto c:value){hash^=static_cast<uint8_t>(c);hash*=1099511628211ULL;}return hash;}std::string normalize(std::string value,uint16_t bound){value=asLowerCaseString(value.substr(0,bound));while(!value.empty()&&std::isspace(static_cast<unsigned char>(value.back())))value.pop_back();return value;}}
BotDialogueObservation BotDialogue::observe(const std::shared_ptr<Player>&player,const BotNpcDialoguePolicy&policy){BotDialogueObservation result;if(!player||!player->getTile())return result;for(const auto &creature:Spectators().find<Creature>(player->getPosition(),false,8,8,6,6).filter<Npc>()){const auto npc=creature->getNpc();if(!npc||!player->canSeeCreature(npc))continue;const auto name=asLowerCaseString(npc->getName());if(!policy.configuredNpcNames.empty()&&std::ranges::find(policy.configuredNpcNames,name)==policy.configuredNpcNames.end())continue;const auto position=npc->getPosition();const bool floor=position.z==player->getPosition().z;result.npcs.push_back({npc->getID(),name,position,static_cast<uint32_t>(std::max(Position::getDistanceX(position,player->getPosition()),Position::getDistanceY(position,player->getPosition()))),true,floor,npc->isInteractingWithPlayer(player->getID()),0});}std::ranges::sort(result.npcs,[](const auto&a,const auto&b){return std::tuple(a.distance,a.normalizedName,a.npcId)<std::tuple(b.distance,b.normalizedName,b.npcId);});uint64_t revision=1469598103934665603ULL;for(auto &npc:result.npcs){revision^=npc.npcId;revision*=1099511628211ULL;revision^=npc.position.x|(static_cast<uint64_t>(npc.position.y)<<16)|(static_cast<uint64_t>(npc.position.z)<<32);revision*=1099511628211ULL;npc.revision=revision;}result.revision=revision;return result;}
std::optional<BotNpcObservation> BotDialogue::select(const BotDialogueObservation&o,const BotNpcDialoguePolicy&policy){for(const auto &npc:o.npcs)if(npc.visible&&npc.sameFloor&&(policy.configuredNpcNames.empty()||std::ranges::find(policy.configuredNpcNames,npc.normalizedName)!=policy.configuredNpcNames.end()))return npc;return std::nullopt;}
const BotDialoguePhrase* BotDialogue::phrase(const BotNpcDialoguePolicy&p,BotDialogueIntent intent){uint8_t topics=0;for(const auto &phrase:p.phrases){if(phrase.intent==BotDialogueIntent::ConfiguredTopic||phrase.intent==BotDialogueIntent::ConfiguredFollowUp){if(topics++>=p.maximumTopics)continue;}if(phrase.intent==intent)return &phrase;}return nullptr;}
BotDialogueResponseObservation BotDialogue::response(const std::shared_ptr<Player>&player,uint32_t npcId,uint64_t after,const BotDialoguePhrase&phrase,uint16_t bound){BotDialogueResponseObservation result{.npcId=npcId};if(!player)return result;for(const auto &speech:player->getVisibleSpeech()){if(speech.revision<=after||speech.speakerId!=npcId)continue;result.revision=speech.revision;result.normalizedToken=normalize(speech.text,bound);result.normalizedTokenHash=hashToken(result.normalizedToken);const auto expected=normalize(phrase.expectedToken,bound);if(!expected.empty()&&result.normalizedToken.find(expected)!=std::string::npos)result.category=phrase.intent==BotDialogueIntent::Greeting?BotDialogueResponse::GreetingAccepted:phrase.intent==BotDialogueIntent::Farewell?BotDialogueResponse::ConversationComplete:BotDialogueResponse::TopicAccepted;else if(result.normalizedToken.find("yes")!=std::string::npos||result.normalizedToken.find("no")!=std::string::npos)result.category=BotDialogueResponse::ConfirmationRequested;else result.category=BotDialogueResponse::UnexpectedResponse;break;}return result;}
std::chrono::milliseconds BotDialogue::backoff(const BotNpcDialoguePolicy&p,uint8_t attempt){uint64_t delay=p.initialBackoff.count();for(uint8_t i=0;i<attempt&&delay<static_cast<uint64_t>(p.maximumBackoff.count());++i)delay=std::min<uint64_t>(delay*2,p.maximumBackoff.count());return std::chrono::milliseconds(delay);}
